# syntax=docker/dockerfile:1
FROM docker:29.6.1-cli AS docker-cli
FROM node:22.23.3-bookworm-slim
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker-cli /usr/local/libexec/docker/cli-plugins /usr/local/lib/docker/cli-plugins
USER node
ENTRYPOINT ["node"]
